# Site settings
title:          bradym.net
tagline:        random thoughts of a code monkey
author:         Brady Mitchell
url:        http://bradym.net

# Options
highlighter:    pygments
permalink:      /:categories/:title.html

# Plugin settings
category_dir:   ''

gems:
  - jekyll-sitemap

exclude: [CNAME, Gemfile, Gemfile.lock, README.md]

timezone: America/Los_Angeles
